import type { DefaulterItem } from "@/lib/defaulters/types";

export type LandlordSort = "az" | "za";

export type DefaultersReportFilters = {
    collector: string;
    landlord: string;
    list: string;
    office: string;
    period: string;
    property: string;
    search: string;
};

export type DefaultersReportPayload = {
    companyName: string;
    defaulters: DefaulterItem[];
    generatedAt: string;
    landlordSort: LandlordSort;
    scope: string;
    selectedFilters: DefaultersReportFilters;
    showOfficeSummary: boolean;
};

type LandlordGroup = {
    landlordId: string;
    landlordName: string;
    officeName: string;
    items: DefaulterItem[];
    totalOutstanding: number;
};

function money(value: number | string | null | undefined) {
    return `UGX ${Math.round(Number(value ?? 0)).toLocaleString()}`;
}

function normalize(value: string | null | undefined) {
    return String(value ?? "").trim().toLowerCase();
}

function landlordSortValue(value: string | null | undefined) {
    return normalize(value || "Unknown landlord");
}

function compareLandlordNames(a: string | null | undefined, b: string | null | undefined, direction: LandlordSort) {
    const comparison = landlordSortValue(a).localeCompare(landlordSortValue(b), undefined, { numeric: true, sensitivity: "base" });
    return direction === "za" ? -comparison : comparison;
}

function compareRoomNumbers(a: string | null | undefined, b: string | null | undefined) {
    return String(a ?? "").trim().localeCompare(String(b ?? "").trim(), undefined, { numeric: true, sensitivity: "base" });
}

export function groupDefaultersByLandlord(items: DefaulterItem[], direction: LandlordSort): LandlordGroup[] {
    const groups = new Map<string, LandlordGroup>();
    for (const item of items) {
        const key = item.landlordId || `unknown:${landlordSortValue(item.landlordName)}:${normalize(item.officeName)}`;
        const group = groups.get(key) ?? {
            landlordId: key,
            landlordName: item.landlordName || "Unknown landlord",
            officeName: item.officeName || "Unknown office",
            items: [],
            totalOutstanding: 0,
        };
        group.items.push(item);
        group.totalOutstanding += item.outstandingBalance;
        groups.set(key, group);
    }
    return [...groups.values()]
        .map((group) => ({ ...group, items: [...group.items].sort((a, b) => compareRoomNumbers(a.roomNumber, b.roomNumber) || normalize(a.tenantName).localeCompare(normalize(b.tenantName))) }))
        .sort((a, b) => compareLandlordNames(a.landlordName, b.landlordName, direction) || normalize(a.officeName).localeCompare(normalize(b.officeName)));
}

function buildOfficeSummary(defaulters: DefaulterItem[]) {
    const offices = new Map<string, { landlordIds: Set<string>; officeName: string; rooms: number; outstanding: number }>();
    for (const item of defaulters) {
        const key = item.officeId || item.officeName;
        const current = offices.get(key) ?? { landlordIds: new Set<string>(), officeName: item.officeName, rooms: 0, outstanding: 0 };
        current.landlordIds.add(item.landlordId || item.landlordName);
        current.rooms += 1;
        current.outstanding += item.outstandingBalance;
        offices.set(key, current);
    }
    return [...offices.values()].sort((a, b) => normalize(a.officeName).localeCompare(normalize(b.officeName)));
}

export function DefaultersReportDocument({ companyName, defaulters, generatedAt, landlordSort, scope, selectedFilters, showOfficeSummary }: DefaultersReportPayload) {
    const landlordGroups = groupDefaultersByLandlord(defaulters, landlordSort);
    const officeSummary = buildOfficeSummary(defaulters);
    const totalOutstanding = landlordGroups.reduce((total, group) => total + group.totalOutstanding, 0);

    return (
        <article className="report-print-document mx-auto bg-white text-slate-950">
            <header className="border-b-2 border-slate-950 pb-4">
                <p className="text-sm font-black uppercase tracking-wide text-slate-500">{companyName}</p>
                <h1 className="mt-1 text-3xl font-black uppercase">Defaulters Report</h1>
                <div className="mt-3 grid gap-2 text-sm font-semibold sm:grid-cols-2 lg:grid-cols-3">
                    <p>Report Date: {new Date(generatedAt).toLocaleDateString()}</p>
                    <p>Selected Office: {scope}</p>
                    <p>Selected Period: {selectedFilters.period}</p>
                    <p>Generated: {new Date(generatedAt).toLocaleString()}</p>
                    <p>Generated By: Ddumba OS</p>
                    <p>Landlord Sort: {landlordSort === "az" ? "A → Z" : "Z → A"}</p>
                </div>
                <p className="mt-3 text-xs font-bold uppercase tracking-wide text-slate-500">
                    Applied Filters: Office: {selectedFilters.office} · Landlord: {selectedFilters.landlord} · Collector: {selectedFilters.collector} · Property: {selectedFilters.property} · List: {selectedFilters.list} · Search: {selectedFilters.search}
                </p>
            </header>
            <section className="mt-5 grid gap-3 sm:grid-cols-3">
                <ReportBox label="Total Landlords" value={landlordGroups.length.toLocaleString()} />
                <ReportBox label="Total Defaulting Rooms" value={defaulters.length.toLocaleString()} />
                <ReportBox label="Total Outstanding" value={money(totalOutstanding)} />
            </section>
            <div className="mt-6 space-y-6">
                {landlordGroups.map((group) => (
                    <section key={`print-landlord:${group.landlordId}`} className="landlord-report-section rounded-2xl border border-slate-300">
                        <div className="landlord-report-heading bg-slate-950 px-4 py-3 text-white">
                            <p className="text-xs font-black uppercase tracking-wide">Landlord</p>
                            <h2 className="text-xl font-black uppercase">{group.landlordName}</h2>
                        </div>
                        <div className="landlord-report-summary grid gap-2 border-b border-slate-200 bg-slate-50 px-4 py-3 text-xs font-bold sm:grid-cols-3">
                            <p><span className="text-slate-500">Office:</span><br />{group.officeName}</p>
                            <p><span className="text-slate-500">Defaulting Rooms:</span><br />{group.items.length.toLocaleString()}</p>
                            <p><span className="text-slate-500">Total Outstanding:</span><br />{money(group.totalOutstanding)}</p>
                        </div>
                        <table className="w-full border-collapse text-xs">
                            <thead>
                                <tr className="bg-slate-100 text-left text-slate-700">
                                    <th className="w-[12%] border border-slate-300 px-3 py-2">Room</th>
                                    <th className="w-[28%] border border-slate-300 px-3 py-2">Tenant</th>
                                    <th className="w-[16%] border border-slate-300 px-3 py-2">Phone</th>
                                    <th className="w-[15%] border border-slate-300 px-3 py-2 text-right">Monthly Rent</th>
                                    <th className="w-[15%] border border-slate-300 px-3 py-2">Last Payment</th>
                                    <th className="w-[14%] border border-slate-300 px-3 py-2 text-right">Outstanding</th>
                                </tr>
                            </thead>
                            <tbody>
                                {group.items.map((item) => (
                                    <tr key={`${item.id}:print:${item.paymentDueDate}`}>
                                        <td className="border border-slate-300 px-3 py-2 font-bold">{item.roomNumber}</td>
                                        <td className="border border-slate-300 px-3 py-2">{item.tenantName}</td>
                                        <td className="border border-slate-300 px-3 py-2">{item.tenantPhone ?? ""}</td>
                                        <td className="border border-slate-300 px-3 py-2 text-right font-bold">{money(item.monthlyRent)}</td>
                                        <td className="border border-slate-300 px-3 py-2">
                                            {item.lastPaymentDate ? (
                                                <>
                                                    <span className="font-bold">{money(item.lastPaymentAmount)}</span>
                                                    <br />
                                                    <span className="text-slate-500">{item.lastPaymentDate}</span>
                                                </>
                                            ) : "No payment"}
                                        </td>
                                        <td className="border border-slate-300 px-3 py-2 text-right font-black">{money(item.outstandingBalance)}</td>
                                    </tr>
                                ))}
                            </tbody>
                            <tfoot>
                                <tr className="bg-slate-50 font-black">
                                    <td className="border border-slate-300 px-3 py-2" colSpan={5}>TOTAL OUTSTANDING</td>
                                    <td className="border border-slate-300 px-3 py-2 text-right">{money(group.totalOutstanding)}</td>
                                </tr>
                            </tfoot>
                        </table>
                    </section>
                ))}
            </div>
            <section className="mt-8 rounded-2xl border-2 border-slate-950 p-4">
                <h2 className="text-lg font-black uppercase">Report Summary</h2>
                <div className="mt-3 grid gap-3 text-sm font-bold sm:grid-cols-2 lg:grid-cols-3">
                    <p>Total Landlords<br /><span className="text-xl font-black">{landlordGroups.length.toLocaleString()}</span></p>
                    <p>Total Defaulting Rooms<br /><span className="text-xl font-black">{defaulters.length.toLocaleString()}</span></p>
                    <p>Total Outstanding<br /><span className="text-xl font-black">{money(totalOutstanding)}</span></p>
                </div>
                {showOfficeSummary ? (
                    <div className="mt-5">
                        <h3 className="text-sm font-black uppercase text-slate-600">Office Summary</h3>
                        <div className="mt-2 grid gap-2 sm:grid-cols-2">
                            {officeSummary.map((office) => (
                                <div key={`office-summary:${office.officeName}`} className="rounded-xl border border-slate-200 p-3 text-sm font-bold">
                                    <p className="font-black uppercase">{office.officeName}</p>
                                    <p>Landlords with defaults: {office.landlordIds.size.toLocaleString()}</p>
                                    <p>Rooms: {office.rooms.toLocaleString()}</p>
                                    <p>Outstanding: {money(office.outstanding)}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                ) : null}
            </section>
            <footer className="mt-10 grid gap-8 text-sm font-semibold sm:grid-cols-2">
                <p>Prepared by: __________________________</p>
                <p>Approved by: __________________________</p>
            </footer>
        </article>
    );
}

function ReportBox({ label, value }: { label: string; value: string }) {
    return (
        <div className="border border-slate-300 p-3">
            <p className="text-xs font-black uppercase text-slate-500">{label}</p>
            <p className="mt-1 text-lg font-black">{value}</p>
        </div>
    );
}
