export const COUNT_TABLES = [
    { key: "landlords", label: "Landlords", table: "landlords" },
    { key: "properties", label: "Properties", table: "properties" },
    { key: "rooms", label: "Rooms", table: "rooms" },
    { key: "tenants", label: "Tenants", table: "tenants" },
    { key: "collections", label: "Collections", table: "collections" },
    { key: "promises", label: "Promises", table: "promises" },
    { key: "expenses", label: "Expenses", table: "expenses" },
    { key: "attendance", label: "Attendance", table: "attendance_events" },
    { key: "dailyReports", label: "Daily reports", table: "office_daily_reports" },
    { key: "landlordPayables", label: "Landlord payables", table: "landlord_monthly_payables" },
    { key: "landlordPayments", label: "Landlord payments", table: "landlord_monthly_payable_payments" },
    { key: "landlordAdvances", label: "Landlord advances", table: "landlord_advances" },
    { key: "recoveryDeductions", label: "Recovery deductions", table: "landlord_debt_deductions" },
    { key: "tenantBalances", label: "Tenant ledger", table: "tenant_ledger_entries" },
    { key: "notifications", label: "Notifications", table: "notifications" },
    { key: "auditLogs", label: "Audit logs", table: "audit_logs" },
    { key: "employees", label: "Employees", table: "employees" },
    { key: "officeUsers", label: "Office users", table: "user_office_roles" },
] as const;
